/* eslint-disable max-lines */
import { COLORS as DefaultColors } from '../../constants/colors';
import type { Theme } from '../themes';

export const Monochrome: Theme[] = [
    {
        name: 'Nexus Original',
        colors: {
            ...DefaultColors,
        },
    },
    {
        name: 'Red Radiance',
        colors: {
            ...DefaultColors,
            Primary: '#FF1A1A',
            Secondary: '#D10000',
            Tertiary: '#FFA6A6',
            PrimaryBackground: '#520000',
            SecondaryBackground: '#660000',
            TertiaryBackground: '#800000',
            AppBackground: '#330000',
            TextInput: '#4A1212',
            ActiveText: '#FFFFFF',
            MainText: '#F0F0F0',
            InactiveText: '#C9C9C9',
        },
    },
    {
        name: 'Orange Ember',
        colors: {
            ...DefaultColors,
            Primary: '#FF8800',
            Secondary: '#CC6600',
            Tertiary: '#FFC28C',
            PrimaryBackground: '#804200',
            SecondaryBackground: '#994c00',
            TertiaryBackground: '#b35c00',
            AppBackground: '#663300',
            TextInput: '#663300',
            ActiveText: '#FFFFFF',
            MainText: '#EFEFEF',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Yellow Glow',
        colors: {
            ...DefaultColors,
            Primary: '#ffea00',
            Secondary: '#E6C800',
            Tertiary: '#FFF5B2',
            PrimaryBackground: '#a08d13',
            SecondaryBackground: '#c8ab04',
            TertiaryBackground: '#e2c803',
            AppBackground: '#998200',
            TextInput: '#665800',
            ActiveText: '#000000',
            MainText: '#222222',
            InactiveText: '#545454',
        },
    },
    {
        name: 'Green Meadow',
        colors: {
            ...DefaultColors,
            Primary: '#00CC00',
            Secondary: '#008800',
            Tertiary: '#A6D9A6',
            PrimaryBackground: '#102410',
            SecondaryBackground: '#204020',
            TertiaryBackground: '#305830',
            AppBackground: '#081208',
            TextInput: '#284628',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#B0B0B0',
        },
    },
    {
        name: 'Cyan Tide',
        colors: {
            ...DefaultColors,
            Primary: '#00D1D1',
            Secondary: '#008080',
            Tertiary: '#B2E5E5',
            PrimaryBackground: '#102829',
            SecondaryBackground: '#1F3F40',
            TertiaryBackground: '#2E5657',
            AppBackground: '#071213',
            TextInput: '#265455',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Blue Depths',
        colors: {
            ...DefaultColors,
            Primary: '#0055FF',
            Secondary: '#0033AA',
            Tertiary: '#A6B8E5',
            PrimaryBackground: '#0D0D33',
            SecondaryBackground: '#1C1C4D',
            TertiaryBackground: '#2B2B66',
            AppBackground: '#080826',
            TextInput: '#24244D',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Pink Blossom',
        colors: {
            ...DefaultColors,
            Primary: '#FF69B4',
            Secondary: '#E75480',
            Tertiary: '#FFD1EA',
            PrimaryBackground: '#7B3552',
            SecondaryBackground: '#A14B77',
            TertiaryBackground: '#C57A9B',
            AppBackground: '#41182B',
            TextInput: '#8A3C62',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#C9C9C9',
        },
    },
    {
        name: 'Magenta Pulse',
        colors: {
            ...DefaultColors,
            Primary: '#E100FF',
            Secondary: '#B300CC',
            Tertiary: '#F6C8FF',
            PrimaryBackground: '#43004D',
            SecondaryBackground: '#62006B',
            TertiaryBackground: '#9100A1',
            AppBackground: '#250026',
            TextInput: '#7C2890',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#B0B0B0',
        },
    },
    {
        name: 'Violet Dream',
        colors: {
            ...DefaultColors,
            Primary: '#9B59B6',
            Secondary: '#6C3483',
            Tertiary: '#E9D6F6',
            PrimaryBackground: '#3E2150',
            SecondaryBackground: '#56316C',
            TertiaryBackground: '#7D4BA1',
            AppBackground: '#231230',
            TextInput: '#6A3B88',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#B0B0B0',
        },
    },
    {
        name: 'Brown Bark',
        colors: {
            ...DefaultColors,
            Primary: '#8B5E3C',
            Secondary: '#6E4322',
            Tertiary: '#D2B48C',
            PrimaryBackground: '#3B2415',
            SecondaryBackground: '#55381F',
            TertiaryBackground: '#8A6038',
            AppBackground: '#24150B',
            TextInput: '#493423',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Silver Steel',
        colors: {
            ...DefaultColors,
            Primary: '#B0BEC5',
            Secondary: '#78909C',
            Tertiary: '#ECEFF1',
            PrimaryBackground: '#34383C',
            SecondaryBackground: '#454A50',
            TertiaryBackground: '#5B6168',
            AppBackground: '#1A1B1D',
            TextInput: '#3D4147',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#E0E0E0',
        },
    },
    {
        name: 'Black Onyx',
        colors: {
            ...DefaultColors,
            Primary: '#111111',
            Secondary: '#222222',
            Tertiary: '#2F2F2F',
            PrimaryBackground: '#1a1a1a',
            SecondaryBackground: '#333333',
            TertiaryBackground: '#4d4d4d',
            AppBackground: '#000000',
            TextInput: '#1C1C1C',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#C9C9C9',
        },
    },
    {
        name: 'White Mist',
        colors: {
            ...DefaultColors,
            Primary: '#FFFFFF',
            Secondary: '#F2F2F2',
            Tertiary: '#FAFAFA',
            PrimaryBackground: '#cccccc',
            SecondaryBackground: '#e6e6e6',
            TertiaryBackground: '#ffffff',
            AppBackground: '#999999',
            TextInput: '#DDDDDD',
            ActiveText: '#111111',
            MainText: '#262626',
            InactiveText: '#595959',
        },
    },
    {
        name: 'Lime Burst',
        colors: {
            ...DefaultColors,
            Primary: '#BFFF00',
            Secondary: '#91D700',
            Tertiary: '#E7FFB2',
            PrimaryBackground: '#53770D',
            SecondaryBackground: '#6B9E13',
            TertiaryBackground: '#91C848',
            AppBackground: '#283A11',
            TextInput: '#5F782A',
            ActiveText: '#000000',
            MainText: '#1a1a1a',
            InactiveText: '#333333',
        },
    },
    {
        name: 'Teal Wave',
        colors: {
            ...DefaultColors,
            Primary: '#00BFAE',
            Secondary: '#00796B',
            Tertiary: '#B2DFDB',
            PrimaryBackground: '#10524A',
            SecondaryBackground: '#19675D',
            TertiaryBackground: '#2E8A7A',
            AppBackground: '#05302B',
            TextInput: '#326863',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Olive Grove',
        colors: {
            ...DefaultColors,
            Primary: '#808000',
            Secondary: '#556B2F',
            Tertiary: '#BFC98F',
            PrimaryBackground: '#383A19',
            SecondaryBackground: '#575C2C',
            TertiaryBackground: '#737A47',
            AppBackground: '#23240D',
            TextInput: '#4D4F1F',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#bababa',
        },
    },
    {
        name: 'Gold Medal',
        colors: {
            ...DefaultColors,
            Primary: '#FFD700',
            Secondary: '#E6C200',
            Tertiary: '#FFF9CC',
            PrimaryBackground: '#998200',
            SecondaryBackground: '#C8AB04',
            TertiaryBackground: '#FFF2B2',
            AppBackground: '#4D4300',
            TextInput: '#665800',
            ActiveText: '#000000',
            MainText: '#262626',
            InactiveText: '#404040',
        },
    },
    {
        name: 'Indigo Night',
        colors: {
            ...DefaultColors,
            Primary: '#4B0082',
            Secondary: '#2E0854',
            Tertiary: '#D1B3FF',
            PrimaryBackground: '#201034',
            SecondaryBackground: '#29194D',
            TertiaryBackground: '#402E73',
            AppBackground: '#120725',
            TextInput: '#31264A',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Peach Cream',
        colors: {
            ...DefaultColors,
            Primary: '#FFDAB9',
            Secondary: '#FFB07C',
            Tertiary: '#FFF2E0',
            PrimaryBackground: '#A76F3C',
            SecondaryBackground: '#C89E77',
            TertiaryBackground: '#FFD2A6',
            AppBackground: '#6E4B28',
            TextInput: '#C8A87A',
            ActiveText: '#000000',
            MainText: '#262626',
            InactiveText: '#4d4d4d',
        },
    },
    {
        name: 'Coral Reef',
        colors: {
            ...DefaultColors,
            Primary: '#FF7F50',
            Secondary: '#E25822',
            Tertiary: '#FFD7C2',
            PrimaryBackground: '#883B21',
            SecondaryBackground: '#AD4E31',
            TertiaryBackground: '#E9967A',
            AppBackground: '#471A0F',
            TextInput: '#BF6E4E',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#C9C9C9',
        },
    },
    {
        name: 'Mint Fresh',
        colors: {
            ...DefaultColors,
            Primary: '#98FF98',
            Secondary: '#34C924',
            Tertiary: '#E0FFE0',
            PrimaryBackground: '#185D2C',
            SecondaryBackground: '#34995E',
            TertiaryBackground: '#A6FFB9',
            AppBackground: '#0E3620',
            TextInput: '#3A7A50',
            ActiveText: '#000000',
            MainText: '#141414',
            InactiveText: '#404040',
        },
    },
    {
        name: 'Navy Royal',
        colors: {
            ...DefaultColors,
            Primary: '#001F6F',
            Secondary: '#004080',
            Tertiary: '#B2BEE5',
            PrimaryBackground: '#0A1733',
            SecondaryBackground: '#1A2952',
            TertiaryBackground: '#364B7A',
            AppBackground: '#071026',
            TextInput: '#283660',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Bronze Forge',
        colors: {
            ...DefaultColors,
            Primary: '#CD7F32',
            Secondary: '#A97142',
            Tertiary: '#FFD8B2',
            PrimaryBackground: '#59371A',
            SecondaryBackground: '#7A4B26',
            TertiaryBackground: '#A77E52',
            AppBackground: '#2F170B',
            TextInput: '#6B4328',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Chartreuse Beam',
        colors: {
            ...DefaultColors,
            Primary: '#DFFF00',
            Secondary: '#B2C900',
            Tertiary: '#F3FFA6',
            PrimaryBackground: '#444F16',
            SecondaryBackground: '#5C670B',
            TertiaryBackground: '#8DAA32',
            AppBackground: '#23290A',
            TextInput: '#697B2D',
            ActiveText: '#000000',
            MainText: '#262626',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Turquoise Coast',
        colors: {
            ...DefaultColors,
            Primary: '#30D5C8',
            Secondary: '#158A85',
            Tertiary: '#B8FFF5',
            PrimaryBackground: '#18615B',
            SecondaryBackground: '#247A73',
            TertiaryBackground: '#37a099',
            AppBackground: '#113D3A',
            TextInput: '#29968B',
            ActiveText: '#FFFFFF',
            MainText: '#e6e6e6',
            InactiveText: '#dedede',
        },
    },
    {
        name: 'Amber Spark',
        colors: {
            ...DefaultColors,
            Primary: '#FFBF00',
            Secondary: '#E6A100',
            Tertiary: '#FFE7B2',
            PrimaryBackground: '#7D6106',
            SecondaryBackground: '#9F7D1A',
            TertiaryBackground: '#FFDC85',
            AppBackground: '#47390A',
            TextInput: '#B79439',
            ActiveText: '#000000',
            MainText: '#262626',
            InactiveText: '#4d4d4d',
        },
    },
    {
        name: 'Ruby Velvet',
        colors: {
            ...DefaultColors,
            Primary: '#9B111E',
            Secondary: '#700D15',
            Tertiary: '#E06C88',
            PrimaryBackground: '#3C1416',
            SecondaryBackground: '#571A21',
            TertiaryBackground: '#962B41',
            AppBackground: '#1C080A',
            TextInput: '#6D2E37',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Slate Sky',
        colors: {
            ...DefaultColors,
            Primary: '#708090',
            Secondary: '#4B5B6B',
            Tertiary: '#B0C4DE',
            PrimaryBackground: '#22272B',
            SecondaryBackground: '#30373E',
            TertiaryBackground: '#46515A',
            AppBackground: '#16191B',
            TextInput: '#2D333A',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#B0B0B0',
        },
    },
    {
        name: 'Rose Petal',
        colors: {
            ...DefaultColors,
            Primary: '#FF66CC',
            Secondary: '#B04282',
            Tertiary: '#FFD6F0',
            PrimaryBackground: '#7A355B',
            SecondaryBackground: '#9E4C80',
            TertiaryBackground: '#CB89B6',
            AppBackground: '#3D1A2E',
            TextInput: '#A26599',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#C9C9C9',
        },
    },
    {
        name: 'Azure Dream',
        colors: {
            ...DefaultColors,
            Primary: '#007FFF',
            Secondary: '#0050A0',
            Tertiary: '#B3DBFF',
            PrimaryBackground: '#0D2640',
            SecondaryBackground: '#17365A',
            TertiaryBackground: '#385DA3',
            AppBackground: '#0A1826',
            TextInput: '#224c77',
            ActiveText: '#FFFFFF',
            MainText: '#ededed',
            InactiveText: '#BBBBBB',
        },
    },
    {
        name: 'Ivory Cloud',
        colors: {
            ...DefaultColors,
            Primary: '#FFFFF0',
            Secondary: '#F6F4E6',
            Tertiary: '#FFFFFF',
            PrimaryBackground: '#F7F6F2',
            SecondaryBackground: '#E9E7DF',
            TertiaryBackground: '#F8F7F1',
            AppBackground: '#DDDBD5',
            TextInput: '#F2F1EC',
            ActiveText: '#0d0d0d',
            MainText: '#262626',
            InactiveText: '#333333',
        },
    },
    {
        name: 'Chocolate Rich',
        colors: {
            ...DefaultColors,
            Primary: '#7B3F00',
            Secondary: '#402107',
            Tertiary: '#D2B48C',
            PrimaryBackground: '#2C1608',
            SecondaryBackground: '#4A2915',
            TertiaryBackground: '#8C5E33',
            AppBackground: '#180C05',
            TextInput: '#5C391A',
            ActiveText: '#FFFFFF',
            MainText: '#C5C5C5',
            InactiveText: '#BBBBBB',
        },
    },
];
