// src/theme/pastel-dreams.ts
import { COLORS as DefaultColors } from '../../constants/colors';
import type { Theme } from '../themes';

export const PastelDreams: Theme[] = [
    {
        name: 'Lavender Cloud',
        colors: {
            ...DefaultColors,
            Primary: '#6B2E85',
            Secondary: '#8F4FB3',
            Tertiary: '#B38ED1',
            PrimaryBackground: '#C1AEDF', // darker
            SecondaryBackground: '#D9C7F0', // mid
            TertiaryBackground: '#EFE7FA', // light
            AppBackground: '#E5DBEE',
            TextInput: '#C9B8D9',
            ActiveText: '#000000',
            MainText: '#2E1F2E',
        },
    },
    {
        name: 'Peach Bliss',
        colors: {
            ...DefaultColors,
            Primary: '#C46B57',
            Secondary: '#E0927C',
            Tertiary: '#F4C4AD',
            PrimaryBackground: '#EACDC4',
            SecondaryBackground: '#F3DED7',
            TertiaryBackground: '#FBEDE9',
            AppBackground: '#F9E9E3',
            TextInput: '#E7CBC4',
            ActiveText: '#000000',
            MainText: '#3A1F18',
        },
    },
    {
        name: 'Mint Whisper',
        colors: {
            ...DefaultColors,
            Primary: '#3A8C7C',
            Secondary: '#60B7A7',
            Tertiary: '#9EE3DA',
            PrimaryBackground: '#BDEAE6',
            SecondaryBackground: '#D4F4F0',
            TertiaryBackground: '#ECFCF8',
            AppBackground: '#DAF6F4',
            TextInput: '#B7E7E2',
            ActiveText: '#000000',
            MainText: '#1F3A36',
        },
    },
    {
        name: 'Baby Blue',
        colors: {
            ...DefaultColors,
            Primary: '#3E99BF',
            Secondary: '#75C2E2',
            Tertiary: '#B4E7F8',
            PrimaryBackground: '#CDEBF7',
            SecondaryBackground: '#E3F7FD',
            TertiaryBackground: '#F5FDFF',
            AppBackground: '#D8F2FB',
            TextInput: '#BEE5F6',
            ActiveText: '#000000',
            MainText: '#1E2F3A',
        },
    },
    {
        name: 'Soft Coral',
        colors: {
            ...DefaultColors,
            Primary: '#B35252',
            Secondary: '#D57878',
            Tertiary: '#E8B0B0',
            PrimaryBackground: '#F8DBDB',
            SecondaryBackground: '#FCEEEE',
            TertiaryBackground: '#FEF9F9',
            AppBackground: '#FCEAEA',
            TextInput: '#EACCCC',
            ActiveText: '#000000',
            MainText: '#3A1F1F',
        },
    },
    {
        name: 'Vanilla Cream',
        colors: {
            ...DefaultColors,
            Primary: '#B8A154',
            Secondary: '#D4BF7E',
            Tertiary: '#EFE9A8',
            PrimaryBackground: '#F3E3B3',
            SecondaryBackground: '#FAEBC2',
            TertiaryBackground: '#FEF6E8',
            AppBackground: '#F9F2E3',
            TextInput: '#E7DCC1',
            ActiveText: '#000000',
            MainText: '#3A321F',
        },
    },
    {
        name: 'Lilac Mist',
        colors: {
            ...DefaultColors,
            Primary: '#7D5480',
            Secondary: '#A07DA7',
            Tertiary: '#C9B1C9',
            PrimaryBackground: '#E6D5E6',
            SecondaryBackground: '#F0E5F0',
            TertiaryBackground: '#FAF6FA',
            AppBackground: '#EDE6ED',
            TextInput: '#D9CAD9',
            ActiveText: '#000000',
            MainText: '#2E1F2E',
        },
    },
    {
        name: 'Honeydew',
        colors: {
            ...DefaultColors,
            Primary: '#6CA36C',
            Secondary: '#98C798',
            Tertiary: '#C5E5C5',
            PrimaryBackground: '#DFF8DF',
            SecondaryBackground: '#EFFFEE',
            TertiaryBackground: '#F8FFFA',
            AppBackground: '#E7F7E7',
            TextInput: '#CCE8CC',
            ActiveText: '#000000',
            MainText: '#1F2E1F',
        },
    },
    {
        name: 'Rosewater',
        colors: {
            ...DefaultColors,
            Primary: '#B26A6A',
            Secondary: '#D69191',
            Tertiary: '#EBCFCF',
            PrimaryBackground: '#F9D8D8',
            SecondaryBackground: '#FDEDED',
            TertiaryBackground: '#FEF9F9',
            AppBackground: '#FBEFEF',
            TextInput: '#E9D8D8',
            ActiveText: '#000000',
            MainText: '#3A1F1F',
        },
    },
    {
        name: 'Pale Sunlight',
        colors: {
            ...DefaultColors,
            Primary: '#B8B24F',
            Secondary: '#D5CF80',
            Tertiary: '#F2EAA8',
            PrimaryBackground: '#F5EFA9',
            SecondaryBackground: '#FBF6CD',
            TertiaryBackground: '#FEFCEE',
            AppBackground: '#FEF9E3',
            TextInput: '#F4EED0',
            ActiveText: '#000000',
            MainText: '#3A321F',
        },
    },
    {
        name: 'Dusky Mauve',
        colors: {
            ...DefaultColors,
            Primary: '#6C415C',
            Secondary: '#8E6E88',
            Tertiary: '#B29DB1',
            PrimaryBackground: '#D3C2D3',
            SecondaryBackground: '#E5D9E5',
            TertiaryBackground: '#F5EFF5',
            AppBackground: '#DED6DA',
            TextInput: '#C9BDC2',
            ActiveText: '#000000',
            MainText: '#2A1F24',
        },
    },
    {
        name: 'Smoky Mint',
        colors: {
            ...DefaultColors,
            Primary: '#3A6B5D',
            Secondary: '#629F8B',
            Tertiary: '#9BC9B8',
            PrimaryBackground: '#C9E2DD',
            SecondaryBackground: '#E0F1EE',
            TertiaryBackground: '#F4FBFA',
            AppBackground: '#D9EAE7',
            TextInput: '#BFDCDC',
            ActiveText: '#000000',
            MainText: '#1F2E2C',
        },
    },
];
