import React, { useCallback } from 'react';

export const DownloadStylesButton: React.FC = () => {
    const handleDownload = useCallback((): void => {
        // Iterate through document.styleSheets to capture all CSS rules,
        // including those generated by CSS‑in‑JS libraries.
        let css = '';
        for (let i = 0; i < document.styleSheets.length; i++) {
            try {
                const sheet = document.styleSheets[i];
                const rules = sheet.cssRules;
                if (rules) {
                    // @ts-expect-error rules
                    for (const rule of rules) {
                        css += `${rule.cssText}\n`;
                    }
                }
            } catch (error) {
                console.error(
                    `Could not access cssRules for sheet at index ${i}:`,
                    error
                );
            }
        }

        // Create a Blob from the aggregated CSS and generate a URL.
        const blob = new Blob([css], { type: 'text/css' });
        const url = URL.createObjectURL(blob);

        // Create a temporary <a> element, set the download attribute,
        // and trigger a click to download the CSS file.
        const link = document.createElement('a');
        link.href = url;
        link.download = 'rnw.css';
        document.body.append(link);
        link.click();
        link.remove();
        URL.revokeObjectURL(url);
    }, []);

    return <button onClick={handleDownload}>Download RN‑Web CSS</button>;
};
