// apps/web/pages/index.tsx
import React from 'react';
import { View, Text, StyleSheet, Image } from 'react-native';
import Head from 'next/head';

// Optionally, load fonts using expo-font/useFonts if desired.
// For simplicity, this example uses system fonts.

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Expo App</title>
                <meta name="description" content="Generated by expo" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <View style={styles.page}>
                <View style={styles.main}>
                    <Image
                        style={styles.logo}
                        source={require('../../public/next.svg')}
                        resizeMode="contain"
                    />
                    <Text style={styles.text}>
                        Get started by editing{' '}
                        <Text style={styles.code}>src/pages/index.tsx</Text>
                    </Text>
                    <Text style={styles.text}>
                        Save and see your changes instantly.
                    </Text>
                    <View style={styles.ctas}>
                        <Text
                            style={styles.primary}
                            onPress={() => {
                                // Replace with appropriate action.
                            }}
                        >
                            <Image
                                style={styles.logoSmall}
                                source={require('../../public/vercel.svg')}
                                resizeMode="contain"
                            />
                            Deploy now
                        </Text>
                        <Text
                            style={styles.secondary}
                            onPress={() => {
                                // Replace with appropriate action.
                            }}
                        >
                            Read our docs
                        </Text>
                    </View>
                </View>
                <View style={styles.footer}>
                    <Text
                        onPress={() => {
                            // Replace with appropriate action.
                        }}
                    >
                        <Image
                            style={styles.icon}
                            source={require('../../public/file.svg')}
                            resizeMode="contain"
                        />
                        Learn
                    </Text>
                    <Text
                        onPress={() => {
                            // Replace with appropriate action.
                        }}
                    >
                        <Image
                            style={styles.icon}
                            source={require('../../public/window.svg')}
                            resizeMode="contain"
                        />
                        Examples
                    </Text>
                    <Text
                        onPress={() => {
                            // Replace with appropriate action.
                        }}
                    >
                        <Image
                            style={styles.icon}
                            source={require('../../public/globe.svg')}
                            resizeMode="contain"
                        />
                        Go to expo.dev →
                    </Text>
                </View>
            </View>
        </>
    );
}

const styles = StyleSheet.create({
    page: {
        flex: 1,
        padding: 20,
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    main: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    logo: {
        width: 180,
        height: 38,
        marginBottom: 16,
    },
    logoSmall: {
        width: 20,
        height: 20,
        marginRight: 8,
    },
    text: {
        fontSize: 16,
        marginVertical: 8,
    },
    code: {
        fontFamily: 'monospace',
        backgroundColor: '#eee',
        padding: 4,
    },
    ctas: {
        flexDirection: 'row',
        marginTop: 16,
    },
    primary: {
        color: 'blue',
        marginRight: 16,
    },
    secondary: {
        color: 'gray',
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        paddingVertical: 16,
        borderTopWidth: 1,
        borderColor: '#ccc',
    },
    icon: {
        width: 16,
        height: 16,
        marginRight: 4,
    },
});
