// src/theme/neon-pulse.ts
import { COLORS as DefaultColors } from '../constants/colors';
import type { Theme } from './themes';

export const NeonPulse: Theme[] = [
    {
        name: 'Electric Blue',
        colors: {
            ...DefaultColors,
            Primary: '#007CAD', // deeper electric blue
            Secondary: '#00E5FF',
            Tertiary: '#4DDFFF',
            PrimaryBackground: '#001A1A', // darker for contrast
            SecondaryBackground: '#002626',
            TertiaryBackground: '#003131',
            AppBackground: '#000F0F',
            TextInput: '#003A3A',
            ActiveText: '#FFFFFF',
            MainText: '#E0E0E0',
        },
    },
    {
        name: 'Neon Pink',
        colors: {
            ...DefaultColors,
            Primary: '#CC00CC',
            Secondary: '#FF10F0',
            Tertiary: '#FF66FF',
            PrimaryBackground: '#1A001A',
            SecondaryBackground: '#260026',
            TertiaryBackground: '#310031',
            AppBackground: '#0F000F',
            TextInput: '#3A003A',
            ActiveText: '#FFFFFF',
            MainText: '#E0E0E0',
        },
    },
    {
        name: 'Lime Shock',
        colors: {
            ...DefaultColors,
            Primary: '#99CC00',
            Secondary: '#CCFF00',
            Tertiary: '#E6FF66',
            PrimaryBackground: '#1A1A00',
            SecondaryBackground: '#262600',
            TertiaryBackground: '#313100',
            AppBackground: '#0F0F00',
            TextInput: '#3A3A00',
            ActiveText: '#FFFFFF',
            MainText: '#E0E0E0',
        },
    },
    {
        name: 'Vibrant Violet',
        colors: {
            ...DefaultColors,
            Primary: '#6E00CC',
            Secondary: '#8F00FF',
            Tertiary: '#BF40FF',
            PrimaryBackground: '#1A001A',
            SecondaryBackground: '#260026',
            TertiaryBackground: '#310031',
            AppBackground: '#0F000F',
            TextInput: '#3A003A',
            ActiveText: '#FFFFFF',
            MainText: '#E0E0E0',
        },
    },
    {
        name: 'Laser Green',
        colors: {
            ...DefaultColors,
            Primary: '#28CC28',
            Secondary: '#39FF14',
            Tertiary: '#66FF66',
            PrimaryBackground: '#001A00',
            SecondaryBackground: '#002600',
            TertiaryBackground: '#003100',
            AppBackground: '#000F00',
            TextInput: '#003A00',
            ActiveText: '#FFFFFF',
            MainText: '#E0E0E0',
        },
    },
    {
        name: 'Hot Coral',
        colors: {
            ...DefaultColors,
            Primary: '#CC3F3F',
            Secondary: '#FF4040',
            Tertiary: '#FF7373',
            PrimaryBackground: '#1A0F0F',
            SecondaryBackground: '#261A1A',
            TertiaryBackground: '#312525',
            AppBackground: '#0F0707',
            TextInput: '#3A1A1A',
            ActiveText: '#FFFFFF',
            MainText: '#E0E0E0',
        },
    },
    {
        name: 'Cyber Yellow',
        colors: {
            ...DefaultColors,
            Primary: '#CCB300',
            Secondary: '#FFD300',
            Tertiary: '#FFE066',
            PrimaryBackground: '#1A1800',
            SecondaryBackground: '#262600',
            TertiaryBackground: '#312F00',
            AppBackground: '#0F0E00',
            TextInput: '#3A3300',
            ActiveText: '#FFFFFF',
            MainText: '#E0E0E0',
        },
    },
    {
        name: 'Fluorescent Red',
        colors: {
            ...DefaultColors,
            Primary: '#CC001F',
            Secondary: '#FF073A',
            Tertiary: '#FF4F6E',
            PrimaryBackground: '#1A0008',
            SecondaryBackground: '#260011',
            TertiaryBackground: '#31001B',
            AppBackground: '#0F0005',
            TextInput: '#3A001F',
            ActiveText: '#FFFFFF',
            MainText: '#E0E0E0',
        },
    },
    {
        name: 'Ultra Aqua',
        colors: {
            ...DefaultColors,
            Primary: '#00CCB3',
            Secondary: '#00FFD1',
            Tertiary: '#66FFF0',
            PrimaryBackground: '#001A17',
            SecondaryBackground: '#002623',
            TertiaryBackground: '#00312D',
            AppBackground: '#000F0C',
            TextInput: '#003A2F',
            ActiveText: '#FFFFFF',
            MainText: '#E0E0E0',
        },
    },
    {
        name: 'Radical Magenta',
        colors: {
            ...DefaultColors,
            Primary: '#CC0099',
            Secondary: '#FF00AF',
            Tertiary: '#FF66C4',
            PrimaryBackground: '#1A0016',
            SecondaryBackground: '#260020',
            TertiaryBackground: '#31002B',
            AppBackground: '#0F000D',
            TextInput: '#3A0031',
            ActiveText: '#FFFFFF',
            MainText: '#E0E0E0',
        },
    },
];
