// src/theme/pastel-dreams.ts
import { COLORS as DefaultColors } from '../constants/colors';
import type { Theme } from './themes';

export const PastelDreams: Theme[] = [
    {
        name: 'Lavender Cloud',
        colors: {
            ...DefaultColors,
            Primary: '#7A3F9A', // deeper lavender
            Secondary: '#A378C9', // richer mid-tone
            Tertiary: '#CBB3E3', // still soft
            PrimaryBackground: '#E8E0F0', // slightly toned
            SecondaryBackground: '#F0EBF5',
            TertiaryBackground: '#F6F2F9',
            AppBackground: '#E5DBEE',
            TextInput: '#C9B8D9',
            ActiveText: '#FFFFFF',
            MainText: '#2E1F2E', // dark enough on backgrounds
        },
    },
    {
        name: 'Peach Bliss',
        colors: {
            ...DefaultColors,
            Primary: '#E58F7C', // warm peach
            Secondary: '#F3B49B',
            Tertiary: '#F9D6C8',
            PrimaryBackground: '#FDECE8',
            SecondaryBackground: '#FEF3F0',
            TertiaryBackground: '#FEF8F6',
            AppBackground: '#F9E9E3',
            TextInput: '#E7CBC4',
            ActiveText: '#FFFFFF',
            MainText: '#3A1F18',
        },
    },
    {
        name: 'Mint Whisper',
        colors: {
            ...DefaultColors,
            Primary: '#4ABFA8',
            Secondary: '#82D5C9',
            Tertiary: '#BEEDE4',
            PrimaryBackground: '#E6F8F6',
            SecondaryBackground: '#EFFCFB',
            TertiaryBackground: '#F6FEFD',
            AppBackground: '#DAF6F4',
            TextInput: '#B7E7E2',
            ActiveText: '#FFFFFF',
            MainText: '#1F3A36',
        },
    },
    {
        name: 'Baby Blue',
        colors: {
            ...DefaultColors,
            Primary: '#5CAFE0',
            Secondary: '#9ED8F7',
            Tertiary: '#CFEFFF',
            PrimaryBackground: '#EAF8FF',
            SecondaryBackground: '#F4FDFF',
            TertiaryBackground: '#FBFEFF',
            AppBackground: '#D8F2FB',
            TextInput: '#BEE5F6',
            ActiveText: '#FFFFFF',
            MainText: '#1E2F3A',
        },
    },
    {
        name: 'Soft Coral',
        colors: {
            ...DefaultColors,
            Primary: '#D66E6E',
            Secondary: '#EE9B9B',
            Tertiary: '#F4CECD',
            PrimaryBackground: '#FFEDED',
            SecondaryBackground: '#FFF4F4',
            TertiaryBackground: '#FFFAFA',
            AppBackground: '#FCEAEA',
            TextInput: '#EACCCC',
            ActiveText: '#FFFFFF',
            MainText: '#3A1F1F',
        },
    },
    {
        name: 'Vanilla Cream',
        colors: {
            ...DefaultColors,
            Primary: '#D4B66A',
            Secondary: '#E6CE94',
            Tertiary: '#F3E4B8',
            PrimaryBackground: '#FFF8E5',
            SecondaryBackground: '#FFFBF0',
            TertiaryBackground: '#FFFEFA',
            AppBackground: '#F9F2E3',
            TextInput: '#E7DCC1',
            ActiveText: '#FFFFFF',
            MainText: '#3A321F',
        },
    },
    {
        name: 'Lilac Mist',
        colors: {
            ...DefaultColors,
            Primary: '#9F6F9F',
            Secondary: '#C4A3C4',
            Tertiary: '#DEC9DE',
            PrimaryBackground: '#F3EDF3',
            SecondaryBackground: '#F8F4F8',
            TertiaryBackground: '#FBF9FB',
            AppBackground: '#EDE6ED',
            TextInput: '#D9CAD9',
            ActiveText: '#FFFFFF',
            MainText: '#2E1F2E',
        },
    },
    {
        name: 'Honeydew',
        colors: {
            ...DefaultColors,
            Primary: '#8FCF8F',
            Secondary: '#B5E5B5',
            Tertiary: '#D8F2D8',
            PrimaryBackground: '#F0FCF0',
            SecondaryBackground: '#F7FEF7',
            TertiaryBackground: '#FBFEFB',
            AppBackground: '#E7F7E7',
            TextInput: '#CCE8CC',
            ActiveText: '#FFFFFF',
            MainText: '#1F2E1F',
        },
    },
    {
        name: 'Rosewater',
        colors: {
            ...DefaultColors,
            Primary: '#D48B8B',
            Secondary: '#ECB8B8',
            Tertiary: '#F4DCDC',
            PrimaryBackground: '#FFF4F4',
            SecondaryBackground: '#FFF8F8',
            TertiaryBackground: '#FFFBFB',
            AppBackground: '#FBEFEF',
            TextInput: '#E9D8D8',
            ActiveText: '#FFFFFF',
            MainText: '#3A1F1F',
        },
    },
    {
        name: 'Pale Sunlight',
        colors: {
            ...DefaultColors,
            Primary: '#E0D16A',
            Secondary: '#F0E894',
            Tertiary: '#F9F1B8',
            PrimaryBackground: '#FFFCED',
            SecondaryBackground: '#FFFEF4',
            TertiaryBackground: '#FFFFFA',
            AppBackground: '#FEF9E3',
            TextInput: '#F4EED0',
            ActiveText: '#FFFFFF',
            MainText: '#3A321F',
        },
    },
    // darker pastel additions:
    {
        name: 'Dusky Mauve',
        colors: {
            ...DefaultColors,
            Primary: '#7A5468',
            Secondary: '#9E7A8E',
            Tertiary: '#BFA3B1',
            PrimaryBackground: '#E8E0E4',
            SecondaryBackground: '#EFE9EB',
            TertiaryBackground: '#F5F2F3',
            AppBackground: '#DED6DA',
            TextInput: '#C9BDC2',
            ActiveText: '#FFFFFF',
            MainText: '#2A1F24',
        },
    },
    {
        name: 'Smoky Mint',
        colors: {
            ...DefaultColors,
            Primary: '#4A7A6E',
            Secondary: '#78A899',
            Tertiary: '#A3C9BF',
            PrimaryBackground: '#E6F2EF',
            SecondaryBackground: '#EFF8F6',
            TertiaryBackground: '#F6FCFB',
            AppBackground: '#D9EAE7',
            TextInput: '#BFDCDC',
            ActiveText: '#FFFFFF',
            MainText: '#1F2E2C',
        },
    },
];
