name: Deploy to Cloud Run

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v0
              with:
                  project_id: hephaestus-418809
                  service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
                  export_default_credentials: true

            # Optional: Cache Docker layers for faster builds in production
            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            # Run your deploy script
            - name: Run Deployment Script
              run: python apps/web/deploy.py
